version: '3.9'

services:
  postgres:
    image: 'postgres:15'
    container_name: postgres_md
    environment:
      - 'POSTGRES_DB=medalist'
      - 'POSTGRES_PASSWORD=test'
      - 'POSTGRES_USER=test'
    ports:
      - '5432:5432'
#    profiles:
#      - pg_15
    networks:
      - net

networks:
  net:
    name: md_net