services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=my_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=my_user'
    ports:
      - '5432:5432'
    profiles:
      - pg_15
