services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=medalist'
      - 'POSTGRES_PASSWORD=test'
      - 'POSTGRES_USER=test'
    ports:
      - '5432:5432'
    profiles:
      - pg_15
