---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  SPRING_PROFILES_ACTIVE: 'prod'
  JAVA_TOOL_OPTIONS: '-XX:+UseContainerSupport -XX:MaxRAMPercentage=80'
  DATA_HOST: '192.168.0.10'
  PREFIX_URL: '/cats'